### ISSUE TITLE
Hello, can you share your dataset files?

### ISSUE THREAD

**Issue by zp678** [melmikaty/3D_CNN#2]

**Comment by melmikaty** [comment]
Hi @zp678 , The dataset I used for this is not available for public use. However, you can use the 3D ShapeNets dataset http://3dshapenets.cs.princeton.edu/ . You may need to modify the code in the  in_data.py file to be able to feed the data to the network.

**Comment by jiangds2018** [comment]
Hello, I want to use your code to do regression prediction about 3D-CNN, my own data is 4D array,the lable is a one-dimensional vector, how should I modify the code?
